// <auto-generated />
using System;
using Comp.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comp.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023094440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Comp.ModelData.Analog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAllCount")
                        .HasColumnType("BIT");

                    b.Property<int>("RelatedComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelatedComponentId");

                    b.HasIndex("SourceComponentId");

                    b.ToTable("Analogs", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.Comp.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeOfElement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConditionalDesignationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenericParametersSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gp1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GpMain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelingOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomenclatureNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypeSizeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAlternative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConditionalDesignationId");

                    b.HasIndex("GenericParametersSetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NomenclatureNumber")
                        .IsUnique();

                    b.HasIndex("TypeSizeId");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsVatTaxpayer")
                        .HasColumnType("BIT");

                    b.Property<string>("MinimumOrderAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementAccount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsitePassword")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Counterparties", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.SortingItems.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("BIT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeliveryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("InvoiceFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Created");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VatStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("VatIncluded");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.ToTable("SupplierOrders", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.TechnicalItems.ConditionalDesignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConditionalDesignations", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.TechnicalItems.GenericParametersSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gp1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gp5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GpMain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GenericParametersSets", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.TechnicalItems.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.TechnicalItems.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.TechnicalItems.TypeSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsingSmd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputsNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TypeSizes", (string)null);
                });

            modelBuilder.Entity("Comp.ModelData.Analog", b =>
                {
                    b.HasOne("Comp.ModelData.Comp.Component", "RelatedComponent")
                        .WithMany()
                        .HasForeignKey("RelatedComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comp.ModelData.Comp.Component", "SourceComponent")
                        .WithMany()
                        .HasForeignKey("SourceComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedComponent");

                    b.Navigation("SourceComponent");
                });

            modelBuilder.Entity("Comp.ModelData.Comp.Component", b =>
                {
                    b.HasOne("Comp.ModelData.SortingItems.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comp.ModelData.TechnicalItems.ConditionalDesignation", "ConditionalDesignation")
                        .WithMany()
                        .HasForeignKey("ConditionalDesignationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comp.ModelData.TechnicalItems.GenericParametersSet", "GenericParametersSet")
                        .WithMany()
                        .HasForeignKey("GenericParametersSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comp.ModelData.TechnicalItems.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comp.ModelData.TechnicalItems.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Comp.ModelData.TechnicalItems.TypeSize", "TypeSize")
                        .WithMany()
                        .HasForeignKey("TypeSizeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ConditionalDesignation");

                    b.Navigation("GenericParametersSet");

                    b.Navigation("Manufacturer");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("TypeSize");
                });

            modelBuilder.Entity("Comp.ModelData.SortingItems.Category", b =>
                {
                    b.HasOne("Comp.ModelData.SortingItems.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Comp.ModelData.SupplierOrder", b =>
                {
                    b.HasOne("Comp.ModelData.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("Comp.ModelData.SortingItems.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
